### ISSUE TITLE
MI > 0.5.4 crashes with 1.17.1

### ISSUE THREAD

**Issue by mtb-xt** [AztechMC/Modern-Industrialization#92]
Hi,

For some reason, when I update Modern Industrialization to 0.5.5 or 0.5.6, my minecraft crashes *_*

Here are the crash logs, I'm not sure if it's because of MI or some other mod, but when I downgrade MI to 0.5.4 - it stops crashing.

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'wthit'!
...
Caused by: java.lang.NoClassDefFoundError: aztech/modern_industrialization/blocks/tank/TankBlockEntity
```

[crash-2021-08-08_12.38.18-client.txt](https://github.com/AztechMC/Modern-Industrialization/files/6950059/crash-2021-08-08_12.38.18-client.txt)
[crash-2021-08-08_12.38.17-server.txt](https://github.com/AztechMC/Modern-Industrialization/files/6950060/crash-2021-08-08_12.38.17-server.txt)

Please let me know if you need any further details

**Comment by bryoung77** [comment]
im having an issue with the game crashing as well with this mod =, i dont get a crash report, but i do have a screen shot of what it does., 
![error](https://user-images.githubusercontent.com/58536735/128617296-54d4516d-5c4d-4fcb-bcfc-8542159bdf74.png)

**Comment by bryoung77** [comment]
i have also checked all the other mods this is the only one that it crashes with.

**Comment by mtb-xt** [comment]
> i have also checked all the other mods this is the only one that it crashes with.

@bryoung77  there should be a `crash-reports` folder in your minecraft folder, you will probably find crash logs there

**Comment by Technici4n** [comment]
Blame megane for relying on MI internals. ^^

**Comment by FreeFull** [comment]
By the way, megane updated 4 hours ago to fix this crash, so you just gotta update now and it should work.
