### ISSUE TITLE
[1.21.1] ADDING_MATERIALS documentation page example scripts throw KubeJS error

### ISSUE THREAD

**Issue by tinybluu** [AztechMC/Modern-Industrialization#1028]
MI: 15.0.140
KJS: 2101.2.7-build.181

The script examples on the ADDING_MATERIALS doc page do not seem to work correctly in neoforge 1.21.1.
Works in 1.20.1 fabric

using this script:
```
MIMaterialEvents.addMaterials(event => {
    event.createMaterial("Zinc", "zinc", 0xd68b7a, builder => {
        builder
            .hardness("soft")
            .materialSet("shiny")
            .addParts("ingot", "nugget", "dust");
    });
});
```

throws this error:
```
[Render thread/ERROR] [KubeJS/]: Startup script errors:
1) materials.js#3: Error in 'MIMaterialEvents.addMaterials': dev.latvian.mods.rhino.EcmaError: TypeError: Cannot find function 
hardness in objectaztech.modern_industrialization.compat.kubejs.material.MaterialBuilderJSWrapper@32492803.
```
whichever function that comes first is the one that is referenced in the log.
